#include:
#  - template: Auto-DevOps.gitlab-ci.yml
stages:
  - production

production:
  stage: production
  script: 
    - echo "Disabled"

publish:  
  image: node:alpine
  stage: production
  ##only:
  # - tags
  #  - triggers
  script:
    - npm install
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm version v1.0.1
    - npm publish --dry-run #${CI_COMMIT_TAG}