include:
  - template: Auto-DevOps.gitlab-ci.yml

variables:
  REVIEW_DISABLED: 'true'

production:
  stage: production
  script: 
    - echo "Disabled"

publish:  
  image: node:alpine
  stage: production
  only:
   - tags
   - triggers
  script:
    - npm install
    - npm run build
    - echo '//registry.npmjs.org/:_authToken=${NPM_TOKEN}'>.npmrc
    - npm version ${CI_COMMIT_TAG}
    - npm publish